import { Download, RotateCcw } from 'lucide-react'
import PolicyOverview from './PolicyOverview'
import HospitalStatus from './HospitalStatus'
import CostCard from './CostCard'
import RiskAssessment from './RiskAssessment'
import ClaimGuidance from './ClaimGuidance'
import RegulatoryCard from './RegulatoryCard'
import NextSteps from './NextSteps'

export default function AuditReport({ report, onReset }) {
  const { sections, riskLevel, claimMode, isNetworkHospital, raw } = report

  function handleDownload() {
    const blob = new Blob([raw], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'Sentinel_Audit_Report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="w-full max-w-3xl mx-auto animate-fade-in" role="region" aria-live="polite" aria-label="Audit report">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-semibold text-slate-800">Surgical Insurance Audit Report</h2>
          <p className="text-sm text-slate-500 mt-0.5">Generated by Sentinel AI · {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-slate-600 border border-slate-300 rounded-xl hover:bg-slate-50 transition-colors"
            aria-label="Download report"
          >
            <Download size={13} /> Download
          </button>
          <button
            onClick={onReset}
            className="flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-indigo-600 border border-indigo-200 rounded-xl hover:bg-indigo-50 transition-colors"
            aria-label="Start new audit"
          >
            <RotateCcw size={13} /> New Audit
          </button>
        </div>
      </div>

      {/* Report sections — 2-col grid on large screens */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {sections.policyOverview && (
          <div className="lg:col-span-2">
            <PolicyOverview text={sections.policyOverview} />
          </div>
        )}
        {sections.hospitalStatus && (
          <HospitalStatus text={sections.hospitalStatus} isNetwork={isNetworkHospital} />
        )}
        {sections.estimatedCost && (
          <CostCard text={sections.estimatedCost} />
        )}
        {sections.riskAssessment && (
          <RiskAssessment text={sections.riskAssessment} riskLevel={riskLevel} />
        )}
        {sections.claimGuidance && (
          <ClaimGuidance text={sections.claimGuidance} claimMode={claimMode} />
        )}
        {sections.regulatorySafeguards && (
          <div className="lg:col-span-2">
            <RegulatoryCard text={sections.regulatorySafeguards} />
          </div>
        )}
        {sections.nextSteps && (
          <div className="lg:col-span-2">
            <NextSteps text={sections.nextSteps} />
          </div>
        )}

        {/* Fallback: if parsing found no sections, show raw report */}
        {Object.keys(sections).length === 0 && (
          <div className="lg:col-span-2 card">
            <p className="section-label mb-3">Audit Report</p>
            <pre className="text-sm text-slate-700 whitespace-pre-wrap font-sans leading-relaxed">{raw}</pre>
          </div>
        )}
      </div>
    </div>
  )
}
